languageCode = "en-us"
title = "Domain Flow Algorithms"
baseURL = "https://stillwater-sc.github.io/domain-flow"
theme = "hugo-theme-learn"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[author]
  name = "Stillwater Supercomputing, Inc."
  email = "theo@stillwater-sc.com"

[params]
  menu = [ "introduction", "design", "blas", "factorization", "matrixkernels", "linearsolvers" ]
  author = "E. Theodore L. Omtzigt"
  description = "Introduction and educational site for the design and optimization of parallel domain flow algorithms"
  showVisitedLinks = true

  # You can use markdown here.
  brand = "Stillwater Supercomputing, Inc."
  topline = "Documentation site for parallel algorithm designers using the Domain Flow model of execution"
  footline = "code with <i class='fa fa-heart'></i>"

  # google analytics tracking id
  googleAnalytics = "UA-2922553-1"

  # Sidebar social links.
  github = "stillwater-sc/domain-flow" # Your Github profile ID
  linkedin = "stillwater-sc" # Your LinkedIn profile ID (from public URL)
  googleplus = "" # Your Google+ profile ID
  facebook = "" # Your Facebook profile ID
  twitter = "" # Your Twitter profile ID
  youtube = ""  # Your Youtube channel ID
  flattr = ""  # populate with your flattr uid
  flickr = "" # Your Flickr profile ID
  vimeo = "" # Your Vimeo profile ID
