languageCode = "en-us"
title = "How to design Domain Flow Algorithms"
baseURL = "http://www.stillwater-sc.com/dfa-docs"
theme = "hugo-theme-learn"
# google analytics tracking id
googleAnalytics = "UA-2922553-1"

[params]
  menu = [ "introduction", "design", "linearalgebra"]